name: ESLint Analysis

on:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint . --format sarif --output-file eslint-results.sarif

      - name: Debug SARIF File
        run: ls -l eslint-results.sarif

      - name: Upload SARIF File
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./eslint-results.sarif
