name: ESLint Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Use a compatible version of Node.js

    - name: Install Dependencies
      run: npm ci

    - name: Install ESLint (if not installed locally)
      run: npm install eslint --save-dev

    - name: Create ESLint Config File (if missing)
      run: |
        if [ ! -f eslint.config.js ]; then
          echo "export default [{ files: ['**/*.js'], rules: { 'no-unused-vars': 'warn' } }];" > eslint.config.js
        fi

    - name: Run ESLint
      run: npx eslint . --format sarif --output-file eslint-results.sarif

    - name: Upload ESLint Results (if required)
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: eslint-results.sarif
